export const movieMock = {
	page: 1,
	results: [
		{
			adult: false,
			backdrop_path: '/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg',
			genre_ids: [28, 18],
			id: 361743,
			original_language: 'en',
			original_title: 'Top Gun: Maverick',
			overview:
				'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
			popularity: 374.687,
			poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
			release_date: '2022-05-24',
			title: 'Top Gun: Maverick',
			video: false,
			vote_average: 8.3,
			vote_count: 5899
		},
		{
			adult: false,
			backdrop_path: '/jILeJ60zPpIjjJHGSmIeY4eO30t.jpg',
			genre_ids: [28, 18],
			id: 744,
			original_language: 'en',
			original_title: 'Top Gun',
			overview:
				"For Lieutenant Pete 'Maverick' Mitchell and his friend and co-pilot Nick 'Goose' Bradshaw, being accepted into an elite training school for fighter pilots is a dream come true. But a tragedy, as well as personal demons, will threaten Pete's dreams of becoming an ace pilot.",
			popularity: 113.897,
			poster_path: '/xUuHj3CgmZQ9P2cMaqQs4J0d4Zc.jpg',
			release_date: '1986-05-16',
			title: 'Top Gun',
			video: false,
			vote_average: 7,
			vote_count: 7029
		},
		{
			adult: false,
			backdrop_path: '/l1GmkC9EJLDVRt8RxT64cet6QUQ.jpg',
			genre_ids: [99, 10770],
			id: 1076135,
			original_language: 'fr',
			original_title: 'Le Phénomène Top Gun Maverick',
			overview:
				'36 years after the release of the first "Top Gun", this sequel has been eagerly awaited by fans around the world. Didier Allouch talks about the success of the film in France and around the world.',
			popularity: 8.502,
			poster_path: '/4t4GS16zOkdewJzeRZZwy3m7Y76.jpg',
			release_date: '2022-12-23',
			title: 'The Top Gun Maverick Phenomenon',
			video: false,
			vote_average: 0,
			vote_count: 0
		},
		{
			adult: false,
			backdrop_path: '/uRokRYuqQZf5v1JJERKhKTmJXLn.jpg',
			genre_ids: [28, 35, 99],
			id: 984430,
			original_language: 'en',
			original_title: "James Corden's Top Gun Training with Tom Cruise",
			overview:
				'When "Top Gun: Maverick" star Tom Cruise calls you up to hang out for the day, you say yes. And for James Corden, that meant having Tom pilot you in two different fighter planes, pushing the limits of gravity and James\'s stomach.',
			popularity: 19.828,
			poster_path: '/e2EILRtu7b6qu4TuwU7BpyHop68.jpg',
			release_date: '2022-06-01',
			title: "James Corden's Top Gun Training with Tom Cruise",
			video: false,
			vote_average: 5.8,
			vote_count: 13
		},
		{
			adult: false,
			backdrop_path: '/6KmDXXNVlbtZVCNQgcWGZeJ5DtS.jpg',
			genre_ids: [99],
			id: 978444,
			original_language: 'fr',
			original_title: 'Top Gun : les coulisses du grand retour',
			overview: '',
			popularity: 13.966,
			poster_path: '/pSs9HbhK5rvHDKlH5YcLTSrPzih.jpg',
			release_date: '2022-05-19',
			title: 'Top Gun : les coulisses du grand retour',
			video: false,
			vote_average: 6.8,
			vote_count: 4
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [99],
			id: 747321,
			original_language: 'en',
			original_title: 'On Your Six: Thirty Years of Top Gun',
			overview:
				'A five-part documentary from 2016, chronicling the legacy of Top Gun.',
			popularity: 11.945,
			poster_path: '/zG78aJ6dnh7s23t4UR25I71FNd6.jpg',
			release_date: '2020-05-19',
			title: 'On Your Six: Thirty Years of Top Gun',
			video: false,
			vote_average: 2,
			vote_count: 1
		},
		{
			adult: false,
			backdrop_path: '/uwOGuf5q0xxUVEfMCy4ooU1S02M.jpg',
			genre_ids: [37],
			id: 243655,
			original_language: 'pt',
			original_title: 'Top Gun',
			overview:
				"A gunslinger returns to his hometown to warn of an impending outlaw gang attack, but he's met with hatred and fear for his previous killings.",
			popularity: 1.678,
			poster_path: '/A4bwWlc6AgWL1cl9LS05pSKdNT7.jpg',
			release_date: '1955-12-01',
			title: 'Top Gun',
			video: false,
			vote_average: 5.8,
			vote_count: 4
		},
		{
			adult: false,
			backdrop_path: '/yp46os3Gf5qOkpDv7rZtxSlP78N.jpg',
			genre_ids: [99],
			id: 520091,
			original_language: 'fr',
			original_title: 'TOP GUN 2002',
			overview: '',
			popularity: 1.306,
			poster_path: '/2lUHMJDIhdeTSUbGFtbzgDEUJ1C.jpg',
			release_date: '2002-07-23',
			title: 'TOP GUN 2002',
			video: false,
			vote_average: 5.5,
			vote_count: 2
		},
		{
			adult: false,
			backdrop_path: '/84Ig8eo770TgXDNBsn4hEgwpgqc.jpg',
			genre_ids: [99],
			id: 976632,
			original_language: 'en',
			original_title: 'The Real Top Gun',
			overview:
				'The story of real mavericks in the Navy’s Top Gun aerial combat school. Action sequences from Hollywood and actual footage from Navy fighters in combat help explore the history of the school and the impact of naval aviation on the world.',
			popularity: 1.416,
			poster_path: '/3YrxKZowAPgbphzaLEfQzfIQg8A.jpg',
			release_date: '2022-05-22',
			title: 'The Real Top Gun',
			video: false,
			vote_average: 4.5,
			vote_count: 2
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [],
			id: 229690,
			original_language: 'pt',
			original_title: 'Top Gun - Mission Norge',
			overview: '',
			popularity: 0.666,
			poster_path: null,
			release_date: '2008-01-01',
			title: 'Top Gun - Mission Norge',
			video: false,
			vote_average: 0,
			vote_count: 0
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [99],
			id: 573425,
			original_language: 'en',
			original_title: 'Combat in the Air - Top Gun',
			overview: '',
			popularity: 1.2,
			poster_path: '/whZNNhnaWWP972rArTYtSVPtSjA.jpg',
			release_date: '1997-04-01',
			title: 'Combat in the Air - Top Gun',
			video: false,
			vote_average: 2,
			vote_count: 1
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [99],
			id: 777254,
			original_language: 'no',
			original_title: 'Top Gun - Oppdrag Norge',
			overview: '',
			popularity: 0.6,
			poster_path: null,
			release_date: '2008-12-14',
			title: 'Top Gun - Oppdrag Norge',
			video: false,
			vote_average: 0,
			vote_count: 0
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [99],
			id: 1022047,
			original_language: 'en',
			original_title: 'Danger Zone: The Making of Top Gun',
			overview:
				'A comprehensive 6-part documentary on the making of "Top Gun" featuring all-new interviews with the cast and crew. Available on Disc 2 of the "Top Gun" 2-Disc Special Collector\'s Edition DVD.',
			popularity: 1.41,
			poster_path: '/fhjM1vsPfjIzHsIC2GE1w5RcfCP.jpg',
			release_date: '2004-05-10',
			title: 'Danger Zone: The Making of Top Gun',
			video: false,
			vote_average: 0,
			vote_count: 0
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [99],
			id: 368986,
			original_language: 'en',
			original_title: 'Top Gun Over Moscow',
			overview:
				"Nova visits Russia for Nova: Top Gun Over Moscow, a thorough look at the sleekest and most powerful Russian jets. In a word, they are tough. These jets are engineered quite differently from their American counterparts. They function well in adverse conditions, able to take off from open dirt fields, and their continuous operation doesn't depend on regular maintenance. The U.S. jet is finely tuned, requiring more frequent upkeep, but definitely having a high-tech edge, particularly in the areas of radar and missile guidance. Interviews with pilots reveal a very different outlook between the two countries on training goals.",
			popularity: 0.6,
			poster_path: null,
			release_date: '2006-10-23',
			title: 'Top Gun Over Moscow',
			video: true,
			vote_average: 0,
			vote_count: 0
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [],
			id: 754461,
			original_language: 'en',
			original_title: 'Top Gun Jets II',
			overview:
				'You\'ll be on board with the world famous Thunderbirds in a spectacular behind-the-scenes demonstration of action, timing, and skill. Experience the heart-stopping starburst maneuver as you become part of the precision teamwork and professionalism that is the United States Air Force.  Prepare for the aerial survival training with the ground and flight crews of "Red Flag." You meet a "bandit" in the solitude of space over the Nevada desert and become "combat ready." And, find yourself in the cockpit of the U.S. Air Force\'s premier fighter -- the incredible F-16 Falcon.  You will "Sour Like an Eagle" after an adrenalin-generating "scramble" in your F-15. Thrill to mach-plus speed and experience the strain of high-G forces as you claim air superiority and execute the "kill." Find out how the men and women in Air Force blue "keep-em flyin\'".',
			popularity: 0.6,
			poster_path: '/6sqFUHPgccPEiEQIlWLBKAO304G.jpg',
			release_date: '',
			title: 'Top Gun Jets II',
			video: true,
			vote_average: 0,
			vote_count: 0
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [10402, 35, 28],
			id: 1062763,
			original_language: 'en',
			original_title: 'A Very Top Gun Christmas: A Musical Parody',
			overview:
				'The North Pole is under attack, and it’s up to Maverick and his elite squad of Top Guns to save the day in this musical parody of 2022’s highest grossing film.',
			popularity: 1.03,
			poster_path: '/funKoLJmx5Lst8Scr1QWqbkCNjU.jpg',
			release_date: '2022-12-14',
			title: 'A Very Top Gun Christmas: A Musical Parody',
			video: false,
			vote_average: 0,
			vote_count: 0
		},
		{
			adult: false,
			backdrop_path: '/gV2wSIlNMIUxEArKYrTF2NX4tjb.jpg',
			genre_ids: [99],
			id: 834027,
			original_language: 'en',
			original_title: 'Val',
			overview:
				'For over 40 years Val Kilmer, one of Hollywood’s most mercurial and/or misunderstood actors has been documenting his own life and craft through film and video. He has amassed thousands of hours of footage, from 16mm home movies made with his brothers, to time spent in iconic roles for blockbuster movies like Top Gun, The Doors, Tombstone, and Batman Forever. This raw, wildly original and unflinching documentary reveals a life lived to extremes and a heart-filled, sometimes hilarious look at what it means to be an artist and a complex man.',
			popularity: 11.448,
			poster_path: '/vWJKmfmjpkFeTbUGep6t7w5TexA.jpg',
			release_date: '2021-07-23',
			title: 'Val',
			video: false,
			vote_average: 7,
			vote_count: 106
		},
		{
			adult: false,
			backdrop_path: '/wQjx0spZDP6ZwYdjQjNKeljbAvQ.jpg',
			genre_ids: [28, 35],
			id: 95094,
			original_language: 'en',
			original_title: 'No. 1 of the Secret Service',
			overview:
				'No. 1 is fearless, irrestible, and licensed to kill. No. 1 is assigned to capture a madman killing international financiers. Before getting the bad guy, No. 1 encounters mercenaries from the evil organization K.R.A.S.H. (Killing, Rape, Arson, Slaughter, and Hit).',
			popularity: 1.964,
			poster_path: '/vKBNaS5LxidxeXYzaLyHSbFIgrT.jpg',
			release_date: '1978-04-01',
			title: 'No. 1 of the Secret Service',
			video: false,
			vote_average: 4.7,
			vote_count: 6
		},
		{
			adult: false,
			backdrop_path: '/eHnS4WjgtoPAPtIXFq2jio4Sh36.jpg',
			genre_ids: [28, 18, 10749],
			id: 124294,
			original_language: 'ko',
			original_title: 'R2B: 리턴 투 베이스',
			overview:
				'Tae-hun causes trouble for the his unit with his antics. He does not take much seriously until a dogfight leaves a pilot dead and another missing. Tae-hun and the other members of his unit launch a rescue mission to prevent a war from breaking out.',
			popularity: 5.779,
			poster_path: '/3Q3PDsxnvh5I3XqgTnAnwdB7uRv.jpg',
			release_date: '2012-08-14',
			title: 'R2B: Return to Base',
			video: false,
			vote_average: 6.2,
			vote_count: 75
		}
	],
	total_pages: 1,
	total_results: 19
};
